import { Image } from "react-native";

export const IconManager = {
  back: require("../assets/icons/back.png"),
  backline: require("../assets/icons/backline.png"),
  playButton: require("../assets/icons/play-button.png"),
  home: require("../assets/icons/home.png"),
  replay: require("../assets/icons/replay.png"),
  next: require("../assets/icons/next.png"),
  whitestar: require("../assets/icons/whitestar.png"),
  history: require("../assets/icons/history.png"),
  movies: {
    previousgold: require("../assets/icons/movies/previousgold.png"),
    nextgold: require("../assets/icons/movies/nextgold.png"),
  },
  correct: require("../assets/icons/correct.png"),
  incorrect: require("../assets/icons/incorrect.png"),
  add: require("../assets/icons/add.png"),
  substract: require("../assets/icons/substract.png"),
  gameItem: {
    donut: require("../assets/icons/donut.png"),
    fries: require("../assets/icons/fries.png"),
    hamburger: require("../assets/icons/hamburger.png"),
    hotdog: require("../assets/icons/hotdog.png"),
    noodle: require("../assets/icons/noodle.png"),
    pizza: require("../assets/icons/pizza.png"),
    ricebowl: require("../assets/icons/rice-bowl.png"),
    salad: require("../assets/icons/salad.png"),
    star: require("../assets/icons/star.png"),
    sushi: require("../assets/icons/sushi.png"),
  },
  star: require("../assets/icons/star.png"),
  heart: require("../assets/icons/heart.png"),
  heartempty: require("../assets/icons/heartempty.png"),
  instruments: {
    drum: require("../assets/icons/instruments/drum.png"),
    piano: require("../assets/icons/instruments/piano.png"),
  },
  games: require("../assets/icons/games.png"),
  feed: require("../assets/icons/feed.png"),
  male: require("../assets/icons/male.png"),
  female: require("../assets/icons/female.png"),
  height: require("../assets/icons/height.png"),
  weight: require("../assets/icons/weight.png"),
  bmi: {
    underweight: require("../assets/icons/bmi/0.png"),
    normal: require("../assets/icons/bmi/1.png"),
    overweight: require("../assets/icons/bmi/2.png"),
    obese: require("../assets/icons/bmi/3.png"),
  },
  edit: require("../assets/icons/edit.png"),
  newentry: require("../assets/icons/newentry.png"),
  roundadd: require("../assets/icons/roundadd.png"),
  equal: require("../assets/icons/equal.png"),
  trash: {
    bananaPeel: require("../assets/icons/trashes/banana-peel.png"),
    bottle: require("../assets/icons/trashes/bottle.png"),
    can: require("../assets/icons/trashes/can.png"),
    can1: require("../assets/icons/trashes/can1.png"),
    can2: require("../assets/icons/trashes/can2.png"),
    cigaretteButt: require("../assets/icons/trashes/cigarette-butt.png"),
    greenPepper: require("../assets/icons/trashes/green-pepper.png"),
    plasticBag: require("../assets/icons/trashes/plastic-bag.png"),
    plasticBags: require("../assets/icons/trashes/plastic-bags.png"),
  },
  avatar: require("../assets/icons/avatar.png"),
  info: require("../assets/icons/info.png"),
  password: require("../assets/icons/password.png"),
  pincode: require("../assets/icons/pincode.png"),
  logout: require("../assets/icons/logout.png"),
  name: require("../assets/icons/name.png"),
  gender: require("../assets/icons/gender.png"),
  cake: require("../assets/icons/cake.png"),
  flame: require("../assets/icons/flame.png"),
  upline: require("../assets/icons/upline.png"),
};

export const ImageManager = {
  number: {
    1: require("../assets/images/number/one.png"),
    2: require("../assets/images/number/two.png"),
    3: require("../assets/images/number/three.png"),
    4: require("../assets/images/number/four.png"),
    5: require("../assets/images/number/five.png"),
    6: require("../assets/images/number/six.png"),
    7: require("../assets/images/number/seven.png"),
    8: require("../assets/images/number/eight.png"),
    9: require("../assets/images/number/nine.png"),
    0: require("../assets/images/number/0.png"),
  },
  alphabet: {
    a: require("../assets/images/alphabet/a.png"),
    letterA: require("../assets/images/alphabet/letterA.png"),
    aw: require("../assets/images/alphabet/aw.png"),
    letterAW: require("../assets/images/alphabet/letterAW.png"),
    aa: require("../assets/images/alphabet/aa.png"),
    letterAA: require("../assets/images/alphabet/letterAA.png"),
    b: require("../assets/images/alphabet/b.png"),
    letterB: require("../assets/images/alphabet/letterB.png"),
    c: require("../assets/images/alphabet/c.png"),
    letterC: require("../assets/images/alphabet/letterC.png"),
    d: require("../assets/images/alphabet/d.png"),
    letterD: require("../assets/images/alphabet/letterD.png"),
    dd: require("../assets/images/alphabet/dd.png"),
    letterDD: require("../assets/images/alphabet/letterDD.png"),
    e: require("../assets/images/alphabet/e.png"),
    letterE: require("../assets/images/alphabet/letterE.png"),
    ee: require("../assets/images/alphabet/ee.png"),
    letterEE: require("../assets/images/alphabet/letterEE.png"),
    g: require("../assets/images/alphabet/g.png"),
    letterG: require("../assets/images/alphabet/letterG.png"),
    h: require("../assets/images/alphabet/h.png"),
    letterH: require("../assets/images/alphabet/letterH.png"),
    i: require("../assets/images/alphabet/i.png"),
    letterI: require("../assets/images/alphabet/letterI.png"),
    k: require("../assets/images/alphabet/k.png"),
    letterK: require("../assets/images/alphabet/letterK.png"),
    l: require("../assets/images/alphabet/l.png"),
    letterL: require("../assets/images/alphabet/letterL.png"),
    m: require("../assets/images/alphabet/m.png"),
    letterM: require("../assets/images/alphabet/letterM.png"),
    n: require("../assets/images/alphabet/n.png"),
    letterN: require("../assets/images/alphabet/letterN.png"),
    o: require("../assets/images/alphabet/o.png"),
    letterO: require("../assets/images/alphabet/letterO.png"),
    oo: require("../assets/images/alphabet/oo.png"),
    letterOO: require("../assets/images/alphabet/letterOO.png"),
    ow: require("../assets/images/alphabet/ow.png"),
    letterOW: require("../assets/images/alphabet/letterOW.png"),
    p: require("../assets/images/alphabet/p.png"),
    letterP: require("../assets/images/alphabet/letterP.png"),
    q: require("../assets/images/alphabet/q.png"),
    letterQ: require("../assets/images/alphabet/letterQ.png"),
    r: require("../assets/images/alphabet/r.png"),
    letterR: require("../assets/images/alphabet/letterR.png"),
    s: require("../assets/images/alphabet/s.png"),
    letterS: require("../assets/images/alphabet/letterS.png"),
    t: require("../assets/images/alphabet/t.png"),
    letterT: require("../assets/images/alphabet/letterT.png"),
    u: require("../assets/images/alphabet/u.png"),
    letterU: require("../assets/images/alphabet/letterU.png"),
    uw: require("../assets/images/alphabet/uw.png"),
    letterUW: require("../assets/images/alphabet/letterUW.png"),
    v: require("../assets/images/alphabet/v.png"),
    letterV: require("../assets/images/alphabet/letterV.png"),
    x: require("../assets/images/alphabet/x.png"),
    letterX: require("../assets/images/alphabet/letterX.png"),
    y: require("../assets/images/alphabet/y.png"),
    letterY: require("../assets/images/alphabet/letterY.png"),
    grid: require("../assets/images/alphabet/grid.jpg"),
  },
  rabbitAndTurtle: {
    forest: [
      require("../assets/images/RabbitAndTurtle/forest0.jpg"),
      require("../assets/images/RabbitAndTurtle/forest1.jpg"),
      require("../assets/images/RabbitAndTurtle/forest2.jpg"),
    ],
    rabbit: [
      require("../assets/images/RabbitAndTurtle/rabbit0.png"),
      require("../assets/images/RabbitAndTurtle/rabbit1.png"),
      require("../assets/images/RabbitAndTurtle/rabbit2.png"),
      require("../assets/images/RabbitAndTurtle/rabbit3.png"),
      require("../assets/images/RabbitAndTurtle/rabbit4.png"),
      require("../assets/images/RabbitAndTurtle/rabbit5.png"),
      require("../assets/images/RabbitAndTurtle/rabbit6.png"),
    ],
    turtle: [
      require("../assets/images/RabbitAndTurtle/turtle0.png"),
      require("../assets/images/RabbitAndTurtle/turtle1.png"),
      require("../assets/images/RabbitAndTurtle/turtle2.png"),
      require("../assets/images/RabbitAndTurtle/turtle3.png"),
      require("../assets/images/RabbitAndTurtle/turtle4.png"),
      require("../assets/images/RabbitAndTurtle/turtle5.png"),
      require("../assets/images/RabbitAndTurtle/turtle6.png"),
      require("../assets/images/RabbitAndTurtle/turtle7.png"),
      require("../assets/images/RabbitAndTurtle/turtle8.png"),
    ],
    snail: [require("../assets/images/RabbitAndTurtle/snail.png")],
  },
  threeHamers: {
    story: [
      require("../assets/images/riu/riu1.jpg"),
      require("../assets/images/riu/riu2.jpg"),
      require("../assets/images/riu/riu3.jpg"),
      require("../assets/images/riu/riu4.jpg"),
      require("../assets/images/riu/riu5.jpg"),
      require("../assets/images/riu/riu6.jpg"),
      require("../assets/images/riu/riu7.jpg"),
      require("../assets/images/riu/riu8.jpg"),
      require("../assets/images/riu/riu9.jpg"),
      require("../assets/images/riu/riu10.jpg"),
      require("../assets/images/riu/riu11.jpg"),
      require("../assets/images/riu/riu12.jpg"),
      require("../assets/images/riu/riu13.jpg"),
      require("../assets/images/riu/riu14.jpg"),
    ],
  },
  instruments: {
    pianobackground: require("../assets/images/instruments/pianobackground.png"),
    drumbackground: require("../assets/images/instruments/drumbackground.png"),
    clap: require("../assets/images/instruments/clap.png"),
    cymbal: require("../assets/images/instruments/cymbal.png"),
    snare: require("../assets/images/instruments/snare.png"),
    kick: require("../assets/images/instruments/kick.png"),
    hihat: require("../assets/images/instruments/hihat.png"),
    maraca: require("../assets/images/instruments/maraca.png"),
  },
  movies: require("../assets/images/movies/movie.png"),
  shapes: {
    beltback: require("../assets/images/shapes/beltback.png"),
    beltfront: require("../assets/images/shapes/beltfront.png"),
    floor: require("../assets/images/shapes/floor.jpg"),
    roundShape: require("../assets/images/shapes/roundshape.png"),
    squareShape: require("../assets/images/shapes/squareshape.png"),
    triangleShape: require("../assets/images/shapes/triangleshape.png"),
    round: [
      require("../assets/images/shapes/round/basketball.png"),
      require("../assets/images/shapes/round/clock.png"),
      require("../assets/images/shapes/round/pizza.png"),
      require("../assets/images/shapes/round/sun.png"),
      require("../assets/images/shapes/round/world.png"),
    ],
    square: [
      require("../assets/images/shapes/square/cracker.png"),
      require("../assets/images/shapes/square/dice.png"),
      require("../assets/images/shapes/square/present.png"),
      require("../assets/images/shapes/square/rubik.png"),
      require("../assets/images/shapes/square/window.png"),
    ],
    triangle: [
      require("../assets/images/shapes/triangle/nonla.png"),
      require("../assets/images/shapes/triangle/pyramid.png"),
      require("../assets/images/shapes/triangle/ruler.png"),
      require("../assets/images/shapes/triangle/warning.png"),
      require("../assets/images/shapes/triangle/watermelon.png"),
    ],
  },
  ground: require("../assets/images/ground.jpg"),
  passwordParent: {
    background: require("../assets/images/passwordparent/background.jpg"),
    animals: require("../assets/images/passwordparent/animals.png"),
    test: require("../assets/images/passwordparent/test.png"),
  },
  gokid: require("../assets/images/gokid.jpg"),
  gokidpng: require("../assets/images/gokid.png"),
  games: {
    instrument: require("../assets/images/games/instrument.png"),
    shapes: require("../assets/images/games/shapes.png"),
    movies: require("../assets/images/games/movies.png"),
    sandbox: require("../assets/images/games/sandbox.png"),
    stories: require("../assets/images/games/stories.png"),
    numbers2: require("../assets/images/games/numbers.png"),
  },
  kidszonebg: require("../assets/images/kidszonebg.jpg"),
  count: {
    bg: require("../assets/images/count/bg.jpg"),
    food: [
      {
        img: require("../assets/images/count/banh.png"),
        name: "cái bánh",
      },
      {
        img: require("../assets/images/count/bo.png"),
        name: "quả bơ",
      },
      {
        img: require("../assets/images/count/cachua.png"),
        name: "quả cà chua",
      },
      {
        img: require("../assets/images/count/cam.png"),
        name: "quả cam",
      },
      {
        img: require("../assets/images/count/coke.png"),
        name: "chai nước ngọt",
      },
      {
        img: require("../assets/images/count/dau.png"),
        name: "quả dâu",
      },
      {
        img: require("../assets/images/count/hamburger.png"),
        name: "cái hamburger",
      },
      {
        img: require("../assets/images/count/kem.png"),
        name: "cây kem",
      },
      {
        img: require("../assets/images/count/le.png"),
        name: "quả lê",
      },
      {
        img: require("../assets/images/count/nho.png"),
        name: "quả nho",
      },
      {
        img: require("../assets/images/count/tao.png"),
        name: "quả táo",
      },
      {
        img: require("../assets/images/count/chanh.png"),
        name: "quả chanh",
      },
      {
        img: require("../assets/images/count/duahau.png"),
        name: "quả dưa hấu",
      },
    ],
  },
};

// Usage: Scale the picture to fit the maxmium 'width' or 'height'.
// Example: original picture: 1000*2000, width: 500, height: null  => Output: (500*1000)
export const autoSize = (source, width, height) => {
  const image = Image.resolveAssetSource(source);
  const ratio = image.width / image.height;

  if (width && !height) {
    return {
      width: width,
      height: width / ratio,
    };
  }
  if (height && !width) {
    return {
      height: height,
      width: height * ratio,
    };
  }
  if (!height && !width) {
    return {
      width: 60,
      height: 60,
    };
  }
};

export const getRandomGameItem = () => {
  var keys = Object.keys(IconManager.gameItem);
  return IconManager.gameItem[keys[(keys.length * Math.random()) << 0]];
};
